name: Trigger Deploy AWS Workflow

on:
  workflow_run:
    workflows: ["Verify Build"]
    types:
      - completed
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger Deploy AWS Workflow
        env:
          WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $WORKFLOW_PAT" \
            https://api.github.com/repos/nocodb/xc-app-2/dispatches \
            -d '{"event_type":"trigger-aws-workflow"}'